package p140me.bridgefy.intro.verification;

import android.content.Context;
import android.os.Build.VERSION;
import android.telephony.PhoneNumberUtils;
import android.telephony.TelephonyManager;
import android.text.TextUtils;
import com.google.i18n.phonenumbers.PhoneNumberUtil;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import net.sqlcipher.database.SQLiteDatabase;
import twitter4j.HttpResponseCode;

/* renamed from: me.bridgefy.intro.verification.h */
/* compiled from: PhoneNumberUtils */
public final class C3583h {

    /* renamed from: a */
    private static final String f9444a = String.valueOf(1);

    /* renamed from: b */
    private static final Locale f9445b = Locale.US;

    /* renamed from: c */
    private static final C3574b f9446c = new C3574b(f9445b, 1);

    /* renamed from: d */
    private static final Map<Integer, List<String>> f9447d = Collections.unmodifiableMap(m10533a());

    /* renamed from: e */
    private static final Map<String, Integer> f9448e = Collections.unmodifiableMap(m10538b());

    /* renamed from: a */
    public static String m10532a(String str, C3574b bVar) {
        if (str.startsWith("+")) {
            return str;
        }
        StringBuilder sb = new StringBuilder();
        sb.append("+");
        sb.append(String.valueOf(bVar.f9392c));
        sb.append(str.replaceAll("[^\\d.]", ""));
        return sb.toString();
    }

    /* renamed from: a */
    public static String m10530a(String str, Context context) {
        C3574b a = m10534a(context);
        if (VERSION.SDK_INT >= 21) {
            return PhoneNumberUtils.formatNumberToE164(str, a.f9391b.getCountry());
        }
        return m10532a(str, a);
    }

    /* renamed from: a */
    static C3574b m10534a(Context context) {
        Locale b = m10537b(context);
        if (b == null) {
            b = m10540c();
        }
        if (b == null) {
            return f9446c;
        }
        Integer b2 = m10536b(b.getCountry());
        return b2 == null ? f9446c : new C3574b(b, b2.intValue());
    }

    /* renamed from: a */
    public static C3582g m10535a(String str) {
        String str2 = f9444a;
        String country = f9445b.getCountry();
        if (str.startsWith("+")) {
            str2 = m10541d(str);
            country = m10539c(str2);
            str = m10531a(str, str2);
        }
        return new C3582g(str, country, str2);
    }

    /* renamed from: c */
    private static String m10539c(String str) {
        List list = (List) f9447d.get(Integer.valueOf(str));
        if (list != null) {
            return (String) list.get(0);
        }
        return f9445b.getCountry();
    }

    /* renamed from: d */
    private static String m10541d(String str) {
        String replaceFirst = str.replaceFirst("^\\+", "");
        int length = replaceFirst.length();
        int i = 1;
        while (i <= 3 && i <= length) {
            String substring = replaceFirst.substring(0, i);
            if (f9447d.containsKey(Integer.valueOf(substring))) {
                return substring;
            }
            i++;
        }
        return f9444a;
    }

    /* renamed from: a */
    private static Map<Integer, List<String>> m10533a() {
        ConcurrentHashMap concurrentHashMap = new ConcurrentHashMap(286);
        ArrayList arrayList = new ArrayList(25);
        arrayList.add("US");
        arrayList.add("AG");
        arrayList.add("AI");
        arrayList.add("AS");
        arrayList.add("BB");
        arrayList.add("BM");
        arrayList.add("BS");
        arrayList.add("CA");
        arrayList.add("DM");
        arrayList.add("DO");
        arrayList.add("GD");
        arrayList.add("GU");
        arrayList.add("JM");
        arrayList.add("KN");
        arrayList.add("KY");
        arrayList.add("LC");
        arrayList.add("MP");
        arrayList.add("MS");
        arrayList.add("PR");
        arrayList.add("SX");
        arrayList.add("TC");
        arrayList.add("TT");
        arrayList.add("VC");
        arrayList.add("VG");
        arrayList.add("VI");
        concurrentHashMap.put(Integer.valueOf(1), arrayList);
        ArrayList arrayList2 = new ArrayList(2);
        arrayList2.add("RU");
        arrayList2.add("KZ");
        concurrentHashMap.put(Integer.valueOf(7), arrayList2);
        ArrayList arrayList3 = new ArrayList(1);
        arrayList3.add("EG");
        concurrentHashMap.put(Integer.valueOf(20), arrayList3);
        ArrayList arrayList4 = new ArrayList(1);
        arrayList4.add("ZA");
        concurrentHashMap.put(Integer.valueOf(27), arrayList4);
        ArrayList arrayList5 = new ArrayList(1);
        arrayList5.add("GR");
        concurrentHashMap.put(Integer.valueOf(30), arrayList5);
        ArrayList arrayList6 = new ArrayList(1);
        arrayList6.add("NL");
        concurrentHashMap.put(Integer.valueOf(31), arrayList6);
        ArrayList arrayList7 = new ArrayList(1);
        arrayList7.add("BE");
        concurrentHashMap.put(Integer.valueOf(32), arrayList7);
        ArrayList arrayList8 = new ArrayList(1);
        arrayList8.add("FR");
        concurrentHashMap.put(Integer.valueOf(33), arrayList8);
        ArrayList arrayList9 = new ArrayList(1);
        arrayList9.add("ES");
        concurrentHashMap.put(Integer.valueOf(34), arrayList9);
        ArrayList arrayList10 = new ArrayList(1);
        arrayList10.add("HU");
        concurrentHashMap.put(Integer.valueOf(36), arrayList10);
        ArrayList arrayList11 = new ArrayList(1);
        arrayList11.add("IT");
        concurrentHashMap.put(Integer.valueOf(39), arrayList11);
        ArrayList arrayList12 = new ArrayList(1);
        arrayList12.add("RO");
        concurrentHashMap.put(Integer.valueOf(40), arrayList12);
        ArrayList arrayList13 = new ArrayList(1);
        arrayList13.add("CH");
        concurrentHashMap.put(Integer.valueOf(41), arrayList13);
        ArrayList arrayList14 = new ArrayList(1);
        arrayList14.add("AT");
        concurrentHashMap.put(Integer.valueOf(43), arrayList14);
        ArrayList arrayList15 = new ArrayList(4);
        arrayList15.add("GB");
        arrayList15.add("GG");
        arrayList15.add("IM");
        arrayList15.add("JE");
        concurrentHashMap.put(Integer.valueOf(44), arrayList15);
        ArrayList arrayList16 = new ArrayList(1);
        arrayList16.add("DK");
        concurrentHashMap.put(Integer.valueOf(45), arrayList16);
        ArrayList arrayList17 = new ArrayList(1);
        arrayList17.add("SE");
        concurrentHashMap.put(Integer.valueOf(46), arrayList17);
        ArrayList arrayList18 = new ArrayList(2);
        arrayList18.add("NO");
        arrayList18.add("SJ");
        concurrentHashMap.put(Integer.valueOf(47), arrayList18);
        ArrayList arrayList19 = new ArrayList(1);
        arrayList19.add("PL");
        concurrentHashMap.put(Integer.valueOf(48), arrayList19);
        ArrayList arrayList20 = new ArrayList(1);
        arrayList20.add("DE");
        concurrentHashMap.put(Integer.valueOf(49), arrayList20);
        ArrayList arrayList21 = new ArrayList(1);
        arrayList21.add("PE");
        concurrentHashMap.put(Integer.valueOf(51), arrayList21);
        ArrayList arrayList22 = new ArrayList(1);
        arrayList22.add("MX");
        concurrentHashMap.put(Integer.valueOf(52), arrayList22);
        ArrayList arrayList23 = new ArrayList(1);
        arrayList23.add("CU");
        concurrentHashMap.put(Integer.valueOf(53), arrayList23);
        ArrayList arrayList24 = new ArrayList(1);
        arrayList24.add("AR");
        concurrentHashMap.put(Integer.valueOf(54), arrayList24);
        ArrayList arrayList25 = new ArrayList(1);
        arrayList25.add("BR");
        concurrentHashMap.put(Integer.valueOf(55), arrayList25);
        ArrayList arrayList26 = new ArrayList(1);
        arrayList26.add("CL");
        concurrentHashMap.put(Integer.valueOf(56), arrayList26);
        ArrayList arrayList27 = new ArrayList(1);
        arrayList27.add("CO");
        concurrentHashMap.put(Integer.valueOf(57), arrayList27);
        ArrayList arrayList28 = new ArrayList(1);
        arrayList28.add("VE");
        concurrentHashMap.put(Integer.valueOf(58), arrayList28);
        ArrayList arrayList29 = new ArrayList(1);
        arrayList29.add("MY");
        concurrentHashMap.put(Integer.valueOf(60), arrayList29);
        ArrayList arrayList30 = new ArrayList(3);
        arrayList30.add("AU");
        arrayList30.add("CC");
        arrayList30.add("CX");
        concurrentHashMap.put(Integer.valueOf(61), arrayList30);
        ArrayList arrayList31 = new ArrayList(1);
        arrayList31.add("ID");
        concurrentHashMap.put(Integer.valueOf(62), arrayList31);
        ArrayList arrayList32 = new ArrayList(1);
        arrayList32.add("PH");
        concurrentHashMap.put(Integer.valueOf(63), arrayList32);
        ArrayList arrayList33 = new ArrayList(1);
        arrayList33.add("NZ");
        concurrentHashMap.put(Integer.valueOf(64), arrayList33);
        ArrayList arrayList34 = new ArrayList(1);
        arrayList34.add("SG");
        concurrentHashMap.put(Integer.valueOf(65), arrayList34);
        ArrayList arrayList35 = new ArrayList(1);
        arrayList35.add("TH");
        concurrentHashMap.put(Integer.valueOf(66), arrayList35);
        ArrayList arrayList36 = new ArrayList(1);
        arrayList36.add("JP");
        concurrentHashMap.put(Integer.valueOf(81), arrayList36);
        ArrayList arrayList37 = new ArrayList(1);
        arrayList37.add("KR");
        concurrentHashMap.put(Integer.valueOf(82), arrayList37);
        ArrayList arrayList38 = new ArrayList(1);
        arrayList38.add("VN");
        concurrentHashMap.put(Integer.valueOf(84), arrayList38);
        ArrayList arrayList39 = new ArrayList(1);
        arrayList39.add("CN");
        concurrentHashMap.put(Integer.valueOf(86), arrayList39);
        ArrayList arrayList40 = new ArrayList(1);
        arrayList40.add("TR");
        concurrentHashMap.put(Integer.valueOf(90), arrayList40);
        ArrayList arrayList41 = new ArrayList(1);
        arrayList41.add("IN");
        concurrentHashMap.put(Integer.valueOf(91), arrayList41);
        ArrayList arrayList42 = new ArrayList(1);
        arrayList42.add("PK");
        concurrentHashMap.put(Integer.valueOf(92), arrayList42);
        ArrayList arrayList43 = new ArrayList(1);
        arrayList43.add("AF");
        concurrentHashMap.put(Integer.valueOf(93), arrayList43);
        ArrayList arrayList44 = new ArrayList(1);
        arrayList44.add("LK");
        concurrentHashMap.put(Integer.valueOf(94), arrayList44);
        ArrayList arrayList45 = new ArrayList(1);
        arrayList45.add("MM");
        concurrentHashMap.put(Integer.valueOf(95), arrayList45);
        ArrayList arrayList46 = new ArrayList(1);
        arrayList46.add("IR");
        concurrentHashMap.put(Integer.valueOf(98), arrayList46);
        ArrayList arrayList47 = new ArrayList(1);
        arrayList47.add("SS");
        concurrentHashMap.put(Integer.valueOf(211), arrayList47);
        ArrayList arrayList48 = new ArrayList(2);
        arrayList48.add("MA");
        arrayList48.add("EH");
        concurrentHashMap.put(Integer.valueOf(212), arrayList48);
        ArrayList arrayList49 = new ArrayList(1);
        arrayList49.add("DZ");
        concurrentHashMap.put(Integer.valueOf(213), arrayList49);
        ArrayList arrayList50 = new ArrayList(1);
        arrayList50.add("TN");
        concurrentHashMap.put(Integer.valueOf(216), arrayList50);
        ArrayList arrayList51 = new ArrayList(1);
        arrayList51.add("LY");
        concurrentHashMap.put(Integer.valueOf(218), arrayList51);
        ArrayList arrayList52 = new ArrayList(1);
        arrayList52.add("GM");
        concurrentHashMap.put(Integer.valueOf(220), arrayList52);
        ArrayList arrayList53 = new ArrayList(1);
        arrayList53.add("SN");
        concurrentHashMap.put(Integer.valueOf(221), arrayList53);
        ArrayList arrayList54 = new ArrayList(1);
        arrayList54.add("MR");
        concurrentHashMap.put(Integer.valueOf(222), arrayList54);
        ArrayList arrayList55 = new ArrayList(1);
        arrayList55.add("ML");
        concurrentHashMap.put(Integer.valueOf(223), arrayList55);
        ArrayList arrayList56 = new ArrayList(1);
        arrayList56.add("GN");
        concurrentHashMap.put(Integer.valueOf(224), arrayList56);
        ArrayList arrayList57 = new ArrayList(1);
        arrayList57.add("CI");
        concurrentHashMap.put(Integer.valueOf(225), arrayList57);
        ArrayList arrayList58 = new ArrayList(1);
        arrayList58.add("BF");
        concurrentHashMap.put(Integer.valueOf(226), arrayList58);
        ArrayList arrayList59 = new ArrayList(1);
        arrayList59.add("NE");
        concurrentHashMap.put(Integer.valueOf(227), arrayList59);
        ArrayList arrayList60 = new ArrayList(1);
        arrayList60.add("TG");
        concurrentHashMap.put(Integer.valueOf(228), arrayList60);
        ArrayList arrayList61 = new ArrayList(1);
        arrayList61.add("BJ");
        concurrentHashMap.put(Integer.valueOf(229), arrayList61);
        ArrayList arrayList62 = new ArrayList(1);
        arrayList62.add("MU");
        concurrentHashMap.put(Integer.valueOf(230), arrayList62);
        ArrayList arrayList63 = new ArrayList(1);
        arrayList63.add("LR");
        concurrentHashMap.put(Integer.valueOf(231), arrayList63);
        ArrayList arrayList64 = new ArrayList(1);
        arrayList64.add("SL");
        concurrentHashMap.put(Integer.valueOf(232), arrayList64);
        ArrayList arrayList65 = new ArrayList(1);
        arrayList65.add("GH");
        concurrentHashMap.put(Integer.valueOf(233), arrayList65);
        ArrayList arrayList66 = new ArrayList(1);
        arrayList66.add("NG");
        concurrentHashMap.put(Integer.valueOf(234), arrayList66);
        ArrayList arrayList67 = new ArrayList(1);
        arrayList67.add("TD");
        concurrentHashMap.put(Integer.valueOf(235), arrayList67);
        ArrayList arrayList68 = new ArrayList(1);
        arrayList68.add("CF");
        concurrentHashMap.put(Integer.valueOf(236), arrayList68);
        ArrayList arrayList69 = new ArrayList(1);
        arrayList69.add("CM");
        concurrentHashMap.put(Integer.valueOf(237), arrayList69);
        ArrayList arrayList70 = new ArrayList(1);
        arrayList70.add("CV");
        concurrentHashMap.put(Integer.valueOf(238), arrayList70);
        ArrayList arrayList71 = new ArrayList(1);
        arrayList71.add("ST");
        concurrentHashMap.put(Integer.valueOf(239), arrayList71);
        ArrayList arrayList72 = new ArrayList(1);
        arrayList72.add("GQ");
        concurrentHashMap.put(Integer.valueOf(240), arrayList72);
        ArrayList arrayList73 = new ArrayList(1);
        arrayList73.add("GA");
        concurrentHashMap.put(Integer.valueOf(241), arrayList73);
        ArrayList arrayList74 = new ArrayList(1);
        arrayList74.add("CG");
        concurrentHashMap.put(Integer.valueOf(242), arrayList74);
        ArrayList arrayList75 = new ArrayList(1);
        arrayList75.add("CD");
        concurrentHashMap.put(Integer.valueOf(243), arrayList75);
        ArrayList arrayList76 = new ArrayList(1);
        arrayList76.add("AO");
        concurrentHashMap.put(Integer.valueOf(244), arrayList76);
        ArrayList arrayList77 = new ArrayList(1);
        arrayList77.add("GW");
        concurrentHashMap.put(Integer.valueOf(245), arrayList77);
        ArrayList arrayList78 = new ArrayList(1);
        arrayList78.add("IO");
        concurrentHashMap.put(Integer.valueOf(246), arrayList78);
        ArrayList arrayList79 = new ArrayList(1);
        arrayList79.add("AC");
        concurrentHashMap.put(Integer.valueOf(247), arrayList79);
        ArrayList arrayList80 = new ArrayList(1);
        arrayList80.add("SC");
        concurrentHashMap.put(Integer.valueOf(248), arrayList80);
        ArrayList arrayList81 = new ArrayList(1);
        arrayList81.add("SD");
        concurrentHashMap.put(Integer.valueOf(249), arrayList81);
        ArrayList arrayList82 = new ArrayList(1);
        arrayList82.add("RW");
        concurrentHashMap.put(Integer.valueOf(SQLiteDatabase.MAX_SQL_CACHE_SIZE), arrayList82);
        ArrayList arrayList83 = new ArrayList(1);
        arrayList83.add("ET");
        concurrentHashMap.put(Integer.valueOf(251), arrayList83);
        ArrayList arrayList84 = new ArrayList(1);
        arrayList84.add("SO");
        concurrentHashMap.put(Integer.valueOf(252), arrayList84);
        ArrayList arrayList85 = new ArrayList(1);
        arrayList85.add("DJ");
        concurrentHashMap.put(Integer.valueOf(253), arrayList85);
        ArrayList arrayList86 = new ArrayList(1);
        arrayList86.add("KE");
        concurrentHashMap.put(Integer.valueOf(254), arrayList86);
        ArrayList arrayList87 = new ArrayList(1);
        arrayList87.add("TZ");
        concurrentHashMap.put(Integer.valueOf(255), arrayList87);
        ArrayList arrayList88 = new ArrayList(1);
        arrayList88.add("UG");
        concurrentHashMap.put(Integer.valueOf(256), arrayList88);
        ArrayList arrayList89 = new ArrayList(1);
        arrayList89.add("BI");
        concurrentHashMap.put(Integer.valueOf(257), arrayList89);
        ArrayList arrayList90 = new ArrayList(1);
        arrayList90.add("MZ");
        concurrentHashMap.put(Integer.valueOf(258), arrayList90);
        ArrayList arrayList91 = new ArrayList(1);
        arrayList91.add("ZM");
        concurrentHashMap.put(Integer.valueOf(260), arrayList91);
        ArrayList arrayList92 = new ArrayList(1);
        arrayList92.add("MG");
        concurrentHashMap.put(Integer.valueOf(261), arrayList92);
        ArrayList arrayList93 = new ArrayList(2);
        arrayList93.add("RE");
        arrayList93.add("YT");
        concurrentHashMap.put(Integer.valueOf(262), arrayList93);
        ArrayList arrayList94 = new ArrayList(1);
        arrayList94.add("ZW");
        concurrentHashMap.put(Integer.valueOf(263), arrayList94);
        ArrayList arrayList95 = new ArrayList(1);
        arrayList95.add("NA");
        concurrentHashMap.put(Integer.valueOf(264), arrayList95);
        ArrayList arrayList96 = new ArrayList(1);
        arrayList96.add("MW");
        concurrentHashMap.put(Integer.valueOf(265), arrayList96);
        ArrayList arrayList97 = new ArrayList(1);
        arrayList97.add("LS");
        concurrentHashMap.put(Integer.valueOf(266), arrayList97);
        ArrayList arrayList98 = new ArrayList(1);
        arrayList98.add("BW");
        concurrentHashMap.put(Integer.valueOf(267), arrayList98);
        ArrayList arrayList99 = new ArrayList(1);
        arrayList99.add("SZ");
        concurrentHashMap.put(Integer.valueOf(268), arrayList99);
        ArrayList arrayList100 = new ArrayList(1);
        arrayList100.add("KM");
        concurrentHashMap.put(Integer.valueOf(269), arrayList100);
        ArrayList arrayList101 = new ArrayList(2);
        arrayList101.add("SH");
        arrayList101.add("TA");
        concurrentHashMap.put(Integer.valueOf(290), arrayList101);
        ArrayList arrayList102 = new ArrayList(1);
        arrayList102.add("ER");
        concurrentHashMap.put(Integer.valueOf(291), arrayList102);
        ArrayList arrayList103 = new ArrayList(1);
        arrayList103.add("AW");
        concurrentHashMap.put(Integer.valueOf(297), arrayList103);
        ArrayList arrayList104 = new ArrayList(1);
        arrayList104.add("FO");
        concurrentHashMap.put(Integer.valueOf(298), arrayList104);
        ArrayList arrayList105 = new ArrayList(1);
        arrayList105.add("GL");
        concurrentHashMap.put(Integer.valueOf(299), arrayList105);
        ArrayList arrayList106 = new ArrayList(1);
        arrayList106.add("GI");
        concurrentHashMap.put(Integer.valueOf(350), arrayList106);
        ArrayList arrayList107 = new ArrayList(1);
        arrayList107.add("PT");
        concurrentHashMap.put(Integer.valueOf(351), arrayList107);
        ArrayList arrayList108 = new ArrayList(1);
        arrayList108.add("LU");
        concurrentHashMap.put(Integer.valueOf(352), arrayList108);
        ArrayList arrayList109 = new ArrayList(1);
        arrayList109.add("IE");
        concurrentHashMap.put(Integer.valueOf(353), arrayList109);
        ArrayList arrayList110 = new ArrayList(1);
        arrayList110.add("IS");
        concurrentHashMap.put(Integer.valueOf(354), arrayList110);
        ArrayList arrayList111 = new ArrayList(1);
        arrayList111.add("AL");
        concurrentHashMap.put(Integer.valueOf(355), arrayList111);
        ArrayList arrayList112 = new ArrayList(1);
        arrayList112.add("MT");
        concurrentHashMap.put(Integer.valueOf(356), arrayList112);
        ArrayList arrayList113 = new ArrayList(1);
        arrayList113.add("CY");
        concurrentHashMap.put(Integer.valueOf(357), arrayList113);
        ArrayList arrayList114 = new ArrayList(2);
        arrayList114.add("FI");
        arrayList114.add("AX");
        concurrentHashMap.put(Integer.valueOf(358), arrayList114);
        ArrayList arrayList115 = new ArrayList(1);
        arrayList115.add("BG");
        concurrentHashMap.put(Integer.valueOf(359), arrayList115);
        ArrayList arrayList116 = new ArrayList(1);
        arrayList116.add("LT");
        concurrentHashMap.put(Integer.valueOf(370), arrayList116);
        ArrayList arrayList117 = new ArrayList(1);
        arrayList117.add("LV");
        concurrentHashMap.put(Integer.valueOf(371), arrayList117);
        ArrayList arrayList118 = new ArrayList(1);
        arrayList118.add("EE");
        concurrentHashMap.put(Integer.valueOf(372), arrayList118);
        ArrayList arrayList119 = new ArrayList(1);
        arrayList119.add("MD");
        concurrentHashMap.put(Integer.valueOf(373), arrayList119);
        ArrayList arrayList120 = new ArrayList(1);
        arrayList120.add("AM");
        concurrentHashMap.put(Integer.valueOf(374), arrayList120);
        ArrayList arrayList121 = new ArrayList(1);
        arrayList121.add("BY");
        concurrentHashMap.put(Integer.valueOf(375), arrayList121);
        ArrayList arrayList122 = new ArrayList(1);
        arrayList122.add("AD");
        concurrentHashMap.put(Integer.valueOf(376), arrayList122);
        ArrayList arrayList123 = new ArrayList(1);
        arrayList123.add("MC");
        concurrentHashMap.put(Integer.valueOf(377), arrayList123);
        ArrayList arrayList124 = new ArrayList(1);
        arrayList124.add("SM");
        concurrentHashMap.put(Integer.valueOf(378), arrayList124);
        ArrayList arrayList125 = new ArrayList(1);
        arrayList125.add("VA");
        concurrentHashMap.put(Integer.valueOf(379), arrayList125);
        ArrayList arrayList126 = new ArrayList(1);
        arrayList126.add("UA");
        concurrentHashMap.put(Integer.valueOf(380), arrayList126);
        ArrayList arrayList127 = new ArrayList(1);
        arrayList127.add("RS");
        concurrentHashMap.put(Integer.valueOf(381), arrayList127);
        ArrayList arrayList128 = new ArrayList(1);
        arrayList128.add("ME");
        concurrentHashMap.put(Integer.valueOf(382), arrayList128);
        ArrayList arrayList129 = new ArrayList(1);
        arrayList129.add("HR");
        concurrentHashMap.put(Integer.valueOf(385), arrayList129);
        ArrayList arrayList130 = new ArrayList(1);
        arrayList130.add("SI");
        concurrentHashMap.put(Integer.valueOf(386), arrayList130);
        ArrayList arrayList131 = new ArrayList(1);
        arrayList131.add("BA");
        concurrentHashMap.put(Integer.valueOf(387), arrayList131);
        ArrayList arrayList132 = new ArrayList(1);
        arrayList132.add("MK");
        concurrentHashMap.put(Integer.valueOf(389), arrayList132);
        ArrayList arrayList133 = new ArrayList(1);
        arrayList133.add("CZ");
        concurrentHashMap.put(Integer.valueOf(HttpResponseCode.ENHANCE_YOUR_CLAIM), arrayList133);
        ArrayList arrayList134 = new ArrayList(1);
        arrayList134.add("SK");
        concurrentHashMap.put(Integer.valueOf(421), arrayList134);
        ArrayList arrayList135 = new ArrayList(1);
        arrayList135.add("LI");
        concurrentHashMap.put(Integer.valueOf(423), arrayList135);
        ArrayList arrayList136 = new ArrayList(1);
        arrayList136.add("FK");
        concurrentHashMap.put(Integer.valueOf(500), arrayList136);
        ArrayList arrayList137 = new ArrayList(1);
        arrayList137.add("BZ");
        concurrentHashMap.put(Integer.valueOf(501), arrayList137);
        ArrayList arrayList138 = new ArrayList(1);
        arrayList138.add("GT");
        concurrentHashMap.put(Integer.valueOf(502), arrayList138);
        ArrayList arrayList139 = new ArrayList(1);
        arrayList139.add("SV");
        concurrentHashMap.put(Integer.valueOf(503), arrayList139);
        ArrayList arrayList140 = new ArrayList(1);
        arrayList140.add("HN");
        concurrentHashMap.put(Integer.valueOf(HttpResponseCode.GATEWAY_TIMEOUT), arrayList140);
        ArrayList arrayList141 = new ArrayList(1);
        arrayList141.add("NI");
        concurrentHashMap.put(Integer.valueOf(505), arrayList141);
        ArrayList arrayList142 = new ArrayList(1);
        arrayList142.add("CR");
        concurrentHashMap.put(Integer.valueOf(506), arrayList142);
        ArrayList arrayList143 = new ArrayList(1);
        arrayList143.add("PA");
        concurrentHashMap.put(Integer.valueOf(507), arrayList143);
        ArrayList arrayList144 = new ArrayList(1);
        arrayList144.add("PM");
        concurrentHashMap.put(Integer.valueOf(508), arrayList144);
        ArrayList arrayList145 = new ArrayList(1);
        arrayList145.add("HT");
        concurrentHashMap.put(Integer.valueOf(509), arrayList145);
        ArrayList arrayList146 = new ArrayList(3);
        arrayList146.add("GP");
        arrayList146.add("BL");
        arrayList146.add("MF");
        concurrentHashMap.put(Integer.valueOf(590), arrayList146);
        ArrayList arrayList147 = new ArrayList(1);
        arrayList147.add("BO");
        concurrentHashMap.put(Integer.valueOf(591), arrayList147);
        ArrayList arrayList148 = new ArrayList(1);
        arrayList148.add("GY");
        concurrentHashMap.put(Integer.valueOf(592), arrayList148);
        ArrayList arrayList149 = new ArrayList(1);
        arrayList149.add("EC");
        concurrentHashMap.put(Integer.valueOf(593), arrayList149);
        ArrayList arrayList150 = new ArrayList(1);
        arrayList150.add("GF");
        concurrentHashMap.put(Integer.valueOf(594), arrayList150);
        ArrayList arrayList151 = new ArrayList(1);
        arrayList151.add("PY");
        concurrentHashMap.put(Integer.valueOf(595), arrayList151);
        ArrayList arrayList152 = new ArrayList(1);
        arrayList152.add("MQ");
        concurrentHashMap.put(Integer.valueOf(596), arrayList152);
        ArrayList arrayList153 = new ArrayList(1);
        arrayList153.add("SR");
        concurrentHashMap.put(Integer.valueOf(597), arrayList153);
        ArrayList arrayList154 = new ArrayList(1);
        arrayList154.add("UY");
        concurrentHashMap.put(Integer.valueOf(598), arrayList154);
        ArrayList arrayList155 = new ArrayList(2);
        arrayList155.add("CW");
        arrayList155.add("BQ");
        concurrentHashMap.put(Integer.valueOf(599), arrayList155);
        ArrayList arrayList156 = new ArrayList(1);
        arrayList156.add("TL");
        concurrentHashMap.put(Integer.valueOf(670), arrayList156);
        ArrayList arrayList157 = new ArrayList(1);
        arrayList157.add("NF");
        concurrentHashMap.put(Integer.valueOf(672), arrayList157);
        ArrayList arrayList158 = new ArrayList(1);
        arrayList158.add("BN");
        concurrentHashMap.put(Integer.valueOf(673), arrayList158);
        ArrayList arrayList159 = new ArrayList(1);
        arrayList159.add("NR");
        concurrentHashMap.put(Integer.valueOf(674), arrayList159);
        ArrayList arrayList160 = new ArrayList(1);
        arrayList160.add("PG");
        concurrentHashMap.put(Integer.valueOf(675), arrayList160);
        ArrayList arrayList161 = new ArrayList(1);
        arrayList161.add("TO");
        concurrentHashMap.put(Integer.valueOf(676), arrayList161);
        ArrayList arrayList162 = new ArrayList(1);
        arrayList162.add("SB");
        concurrentHashMap.put(Integer.valueOf(677), arrayList162);
        ArrayList arrayList163 = new ArrayList(1);
        arrayList163.add("VU");
        concurrentHashMap.put(Integer.valueOf(678), arrayList163);
        ArrayList arrayList164 = new ArrayList(1);
        arrayList164.add("FJ");
        concurrentHashMap.put(Integer.valueOf(679), arrayList164);
        ArrayList arrayList165 = new ArrayList(1);
        arrayList165.add("PW");
        concurrentHashMap.put(Integer.valueOf(680), arrayList165);
        ArrayList arrayList166 = new ArrayList(1);
        arrayList166.add("WF");
        concurrentHashMap.put(Integer.valueOf(681), arrayList166);
        ArrayList arrayList167 = new ArrayList(1);
        arrayList167.add("CK");
        concurrentHashMap.put(Integer.valueOf(682), arrayList167);
        ArrayList arrayList168 = new ArrayList(1);
        arrayList168.add("NU");
        concurrentHashMap.put(Integer.valueOf(683), arrayList168);
        ArrayList arrayList169 = new ArrayList(1);
        arrayList169.add("WS");
        concurrentHashMap.put(Integer.valueOf(685), arrayList169);
        ArrayList arrayList170 = new ArrayList(1);
        arrayList170.add("KI");
        concurrentHashMap.put(Integer.valueOf(686), arrayList170);
        ArrayList arrayList171 = new ArrayList(1);
        arrayList171.add("NC");
        concurrentHashMap.put(Integer.valueOf(687), arrayList171);
        ArrayList arrayList172 = new ArrayList(1);
        arrayList172.add("TV");
        concurrentHashMap.put(Integer.valueOf(688), arrayList172);
        ArrayList arrayList173 = new ArrayList(1);
        arrayList173.add("PF");
        concurrentHashMap.put(Integer.valueOf(689), arrayList173);
        ArrayList arrayList174 = new ArrayList(1);
        arrayList174.add("TK");
        concurrentHashMap.put(Integer.valueOf(690), arrayList174);
        ArrayList arrayList175 = new ArrayList(1);
        arrayList175.add("FM");
        concurrentHashMap.put(Integer.valueOf(691), arrayList175);
        ArrayList arrayList176 = new ArrayList(1);
        arrayList176.add("MH");
        concurrentHashMap.put(Integer.valueOf(692), arrayList176);
        ArrayList arrayList177 = new ArrayList(1);
        arrayList177.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        concurrentHashMap.put(Integer.valueOf(800), arrayList177);
        ArrayList arrayList178 = new ArrayList(1);
        arrayList178.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        concurrentHashMap.put(Integer.valueOf(808), arrayList178);
        ArrayList arrayList179 = new ArrayList(1);
        arrayList179.add("KP");
        concurrentHashMap.put(Integer.valueOf(850), arrayList179);
        ArrayList arrayList180 = new ArrayList(1);
        arrayList180.add("HK");
        concurrentHashMap.put(Integer.valueOf(852), arrayList180);
        ArrayList arrayList181 = new ArrayList(1);
        arrayList181.add("MO");
        concurrentHashMap.put(Integer.valueOf(853), arrayList181);
        ArrayList arrayList182 = new ArrayList(1);
        arrayList182.add("KH");
        concurrentHashMap.put(Integer.valueOf(855), arrayList182);
        ArrayList arrayList183 = new ArrayList(1);
        arrayList183.add("LA");
        concurrentHashMap.put(Integer.valueOf(856), arrayList183);
        ArrayList arrayList184 = new ArrayList(1);
        arrayList184.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        concurrentHashMap.put(Integer.valueOf(870), arrayList184);
        ArrayList arrayList185 = new ArrayList(1);
        arrayList185.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        concurrentHashMap.put(Integer.valueOf(878), arrayList185);
        ArrayList arrayList186 = new ArrayList(1);
        arrayList186.add("BD");
        concurrentHashMap.put(Integer.valueOf(880), arrayList186);
        ArrayList arrayList187 = new ArrayList(1);
        arrayList187.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        concurrentHashMap.put(Integer.valueOf(881), arrayList187);
        ArrayList arrayList188 = new ArrayList(1);
        arrayList188.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        concurrentHashMap.put(Integer.valueOf(882), arrayList188);
        ArrayList arrayList189 = new ArrayList(1);
        arrayList189.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        concurrentHashMap.put(Integer.valueOf(883), arrayList189);
        ArrayList arrayList190 = new ArrayList(1);
        arrayList190.add("TW");
        concurrentHashMap.put(Integer.valueOf(886), arrayList190);
        ArrayList arrayList191 = new ArrayList(1);
        arrayList191.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        concurrentHashMap.put(Integer.valueOf(888), arrayList191);
        ArrayList arrayList192 = new ArrayList(1);
        arrayList192.add("MV");
        concurrentHashMap.put(Integer.valueOf(960), arrayList192);
        ArrayList arrayList193 = new ArrayList(1);
        arrayList193.add("LB");
        concurrentHashMap.put(Integer.valueOf(961), arrayList193);
        ArrayList arrayList194 = new ArrayList(1);
        arrayList194.add("JO");
        concurrentHashMap.put(Integer.valueOf(962), arrayList194);
        ArrayList arrayList195 = new ArrayList(1);
        arrayList195.add("SY");
        concurrentHashMap.put(Integer.valueOf(963), arrayList195);
        ArrayList arrayList196 = new ArrayList(1);
        arrayList196.add("IQ");
        concurrentHashMap.put(Integer.valueOf(964), arrayList196);
        ArrayList arrayList197 = new ArrayList(1);
        arrayList197.add("KW");
        concurrentHashMap.put(Integer.valueOf(965), arrayList197);
        ArrayList arrayList198 = new ArrayList(1);
        arrayList198.add("SA");
        concurrentHashMap.put(Integer.valueOf(966), arrayList198);
        ArrayList arrayList199 = new ArrayList(1);
        arrayList199.add("YE");
        concurrentHashMap.put(Integer.valueOf(967), arrayList199);
        ArrayList arrayList200 = new ArrayList(1);
        arrayList200.add("OM");
        concurrentHashMap.put(Integer.valueOf(968), arrayList200);
        ArrayList arrayList201 = new ArrayList(1);
        arrayList201.add("PS");
        concurrentHashMap.put(Integer.valueOf(970), arrayList201);
        ArrayList arrayList202 = new ArrayList(1);
        arrayList202.add("AE");
        concurrentHashMap.put(Integer.valueOf(971), arrayList202);
        ArrayList arrayList203 = new ArrayList(1);
        arrayList203.add("IL");
        concurrentHashMap.put(Integer.valueOf(972), arrayList203);
        ArrayList arrayList204 = new ArrayList(1);
        arrayList204.add("BH");
        concurrentHashMap.put(Integer.valueOf(973), arrayList204);
        ArrayList arrayList205 = new ArrayList(1);
        arrayList205.add("QA");
        concurrentHashMap.put(Integer.valueOf(974), arrayList205);
        ArrayList arrayList206 = new ArrayList(1);
        arrayList206.add("BT");
        concurrentHashMap.put(Integer.valueOf(975), arrayList206);
        ArrayList arrayList207 = new ArrayList(1);
        arrayList207.add("MN");
        concurrentHashMap.put(Integer.valueOf(976), arrayList207);
        ArrayList arrayList208 = new ArrayList(1);
        arrayList208.add("NP");
        concurrentHashMap.put(Integer.valueOf(977), arrayList208);
        ArrayList arrayList209 = new ArrayList(1);
        arrayList209.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        concurrentHashMap.put(Integer.valueOf(979), arrayList209);
        ArrayList arrayList210 = new ArrayList(1);
        arrayList210.add("TJ");
        concurrentHashMap.put(Integer.valueOf(992), arrayList210);
        ArrayList arrayList211 = new ArrayList(1);
        arrayList211.add("TM");
        concurrentHashMap.put(Integer.valueOf(993), arrayList211);
        ArrayList arrayList212 = new ArrayList(1);
        arrayList212.add("AZ");
        concurrentHashMap.put(Integer.valueOf(994), arrayList212);
        ArrayList arrayList213 = new ArrayList(1);
        arrayList213.add("GE");
        concurrentHashMap.put(Integer.valueOf(995), arrayList213);
        ArrayList arrayList214 = new ArrayList(1);
        arrayList214.add("KG");
        concurrentHashMap.put(Integer.valueOf(996), arrayList214);
        ArrayList arrayList215 = new ArrayList(1);
        arrayList215.add("UZ");
        concurrentHashMap.put(Integer.valueOf(998), arrayList215);
        return concurrentHashMap;
    }

    /* renamed from: b */
    private static synchronized Map<String, Integer> m10538b() {
        HashMap hashMap;
        synchronized (C3583h.class) {
            hashMap = new HashMap(291);
            hashMap.put("AF", Integer.valueOf(93));
            hashMap.put("AX", Integer.valueOf(358));
            hashMap.put("AL", Integer.valueOf(355));
            hashMap.put("DZ", Integer.valueOf(213));
            hashMap.put("AS", Integer.valueOf(1));
            hashMap.put("AD", Integer.valueOf(376));
            hashMap.put("AO", Integer.valueOf(244));
            hashMap.put("AI", Integer.valueOf(1));
            hashMap.put("AG", Integer.valueOf(1));
            hashMap.put("AR", Integer.valueOf(54));
            hashMap.put("AM", Integer.valueOf(374));
            hashMap.put("AW", Integer.valueOf(297));
            hashMap.put("AC", Integer.valueOf(247));
            hashMap.put("AU", Integer.valueOf(61));
            hashMap.put("AT", Integer.valueOf(43));
            hashMap.put("AZ", Integer.valueOf(994));
            hashMap.put("BS", Integer.valueOf(1));
            hashMap.put("BH", Integer.valueOf(973));
            hashMap.put("BD", Integer.valueOf(880));
            hashMap.put("BB", Integer.valueOf(1));
            hashMap.put("BY", Integer.valueOf(375));
            hashMap.put("BE", Integer.valueOf(32));
            hashMap.put("BZ", Integer.valueOf(501));
            hashMap.put("BJ", Integer.valueOf(229));
            hashMap.put("BM", Integer.valueOf(1));
            hashMap.put("BT", Integer.valueOf(975));
            hashMap.put("BO", Integer.valueOf(591));
            hashMap.put("BA", Integer.valueOf(387));
            hashMap.put("BW", Integer.valueOf(267));
            hashMap.put("BR", Integer.valueOf(55));
            hashMap.put("IO", Integer.valueOf(246));
            hashMap.put("VG", Integer.valueOf(1));
            hashMap.put("BN", Integer.valueOf(673));
            hashMap.put("BG", Integer.valueOf(359));
            hashMap.put("BF", Integer.valueOf(226));
            hashMap.put("BI", Integer.valueOf(257));
            hashMap.put("KH", Integer.valueOf(855));
            hashMap.put("CM", Integer.valueOf(237));
            hashMap.put("CA", Integer.valueOf(1));
            hashMap.put("CV", Integer.valueOf(238));
            hashMap.put("BQ", Integer.valueOf(599));
            hashMap.put("KY", Integer.valueOf(1));
            hashMap.put("CF", Integer.valueOf(236));
            hashMap.put("TD", Integer.valueOf(235));
            hashMap.put("CL", Integer.valueOf(56));
            hashMap.put("CN", Integer.valueOf(86));
            hashMap.put("CX", Integer.valueOf(61));
            hashMap.put("CC", Integer.valueOf(61));
            hashMap.put("CO", Integer.valueOf(57));
            hashMap.put("KM", Integer.valueOf(269));
            hashMap.put("CD", Integer.valueOf(243));
            hashMap.put("CG", Integer.valueOf(242));
            hashMap.put("CK", Integer.valueOf(682));
            hashMap.put("CR", Integer.valueOf(506));
            hashMap.put("CI", Integer.valueOf(225));
            hashMap.put("HR", Integer.valueOf(385));
            hashMap.put("CU", Integer.valueOf(53));
            hashMap.put("CW", Integer.valueOf(599));
            hashMap.put("CY", Integer.valueOf(357));
            hashMap.put("CZ", Integer.valueOf(HttpResponseCode.ENHANCE_YOUR_CLAIM));
            hashMap.put("DK", Integer.valueOf(45));
            hashMap.put("DJ", Integer.valueOf(253));
            hashMap.put("DM", Integer.valueOf(1));
            hashMap.put("DO", Integer.valueOf(1));
            hashMap.put("TL", Integer.valueOf(670));
            hashMap.put("EC", Integer.valueOf(593));
            hashMap.put("EG", Integer.valueOf(20));
            hashMap.put("SV", Integer.valueOf(503));
            hashMap.put("GQ", Integer.valueOf(240));
            hashMap.put("ER", Integer.valueOf(291));
            hashMap.put("EE", Integer.valueOf(372));
            hashMap.put("ET", Integer.valueOf(251));
            hashMap.put("FK", Integer.valueOf(500));
            hashMap.put("FO", Integer.valueOf(298));
            hashMap.put("FJ", Integer.valueOf(679));
            hashMap.put("FI", Integer.valueOf(358));
            hashMap.put("FR", Integer.valueOf(33));
            hashMap.put("GF", Integer.valueOf(594));
            hashMap.put("PF", Integer.valueOf(689));
            hashMap.put("GA", Integer.valueOf(241));
            hashMap.put("GM", Integer.valueOf(220));
            hashMap.put("GE", Integer.valueOf(995));
            hashMap.put("DE", Integer.valueOf(49));
            hashMap.put("GH", Integer.valueOf(233));
            hashMap.put("GI", Integer.valueOf(350));
            hashMap.put("GR", Integer.valueOf(30));
            hashMap.put("GL", Integer.valueOf(299));
            hashMap.put("GD", Integer.valueOf(1));
            hashMap.put("GP", Integer.valueOf(590));
            hashMap.put("GU", Integer.valueOf(1));
            hashMap.put("GT", Integer.valueOf(502));
            hashMap.put("GG", Integer.valueOf(44));
            hashMap.put("GN", Integer.valueOf(224));
            hashMap.put("GW", Integer.valueOf(245));
            hashMap.put("GY", Integer.valueOf(592));
            hashMap.put("HT", Integer.valueOf(509));
            hashMap.put("HM", Integer.valueOf(672));
            hashMap.put("HN", Integer.valueOf(HttpResponseCode.GATEWAY_TIMEOUT));
            hashMap.put("HK", Integer.valueOf(852));
            hashMap.put("HU", Integer.valueOf(36));
            hashMap.put("IS", Integer.valueOf(354));
            hashMap.put("IN", Integer.valueOf(91));
            hashMap.put("ID", Integer.valueOf(62));
            hashMap.put("IR", Integer.valueOf(98));
            hashMap.put("IQ", Integer.valueOf(964));
            hashMap.put("IE", Integer.valueOf(353));
            hashMap.put("IM", Integer.valueOf(44));
            hashMap.put("IL", Integer.valueOf(972));
            hashMap.put("IT", Integer.valueOf(39));
            hashMap.put("JM", Integer.valueOf(1));
            hashMap.put("JP", Integer.valueOf(81));
            hashMap.put("JE", Integer.valueOf(44));
            hashMap.put("JO", Integer.valueOf(962));
            hashMap.put("KZ", Integer.valueOf(7));
            hashMap.put("KE", Integer.valueOf(254));
            hashMap.put("KI", Integer.valueOf(686));
            hashMap.put("XK", Integer.valueOf(381));
            hashMap.put("KW", Integer.valueOf(965));
            hashMap.put("KG", Integer.valueOf(996));
            hashMap.put("LA", Integer.valueOf(856));
            hashMap.put("LV", Integer.valueOf(371));
            hashMap.put("LB", Integer.valueOf(961));
            hashMap.put("LS", Integer.valueOf(266));
            hashMap.put("LR", Integer.valueOf(231));
            hashMap.put("LY", Integer.valueOf(218));
            hashMap.put("LI", Integer.valueOf(423));
            hashMap.put("LT", Integer.valueOf(370));
            hashMap.put("LU", Integer.valueOf(352));
            hashMap.put("MO", Integer.valueOf(853));
            hashMap.put("MK", Integer.valueOf(389));
            hashMap.put("MG", Integer.valueOf(261));
            hashMap.put("MW", Integer.valueOf(265));
            hashMap.put("MY", Integer.valueOf(60));
            hashMap.put("MV", Integer.valueOf(960));
            hashMap.put("ML", Integer.valueOf(223));
            hashMap.put("MT", Integer.valueOf(356));
            hashMap.put("MH", Integer.valueOf(692));
            hashMap.put("MQ", Integer.valueOf(596));
            hashMap.put("MR", Integer.valueOf(222));
            hashMap.put("MU", Integer.valueOf(230));
            hashMap.put("YT", Integer.valueOf(262));
            hashMap.put("MX", Integer.valueOf(52));
            hashMap.put("FM", Integer.valueOf(691));
            hashMap.put("MD", Integer.valueOf(373));
            hashMap.put("MC", Integer.valueOf(377));
            hashMap.put("MN", Integer.valueOf(976));
            hashMap.put("ME", Integer.valueOf(382));
            hashMap.put("MS", Integer.valueOf(1));
            hashMap.put("MA", Integer.valueOf(212));
            hashMap.put("MZ", Integer.valueOf(258));
            hashMap.put("MM", Integer.valueOf(95));
            hashMap.put("NA", Integer.valueOf(264));
            hashMap.put("NR", Integer.valueOf(674));
            hashMap.put("NP", Integer.valueOf(977));
            hashMap.put("NL", Integer.valueOf(31));
            hashMap.put("NC", Integer.valueOf(687));
            hashMap.put("NZ", Integer.valueOf(64));
            hashMap.put("NI", Integer.valueOf(505));
            hashMap.put("NE", Integer.valueOf(227));
            hashMap.put("NG", Integer.valueOf(234));
            hashMap.put("NU", Integer.valueOf(683));
            hashMap.put("NF", Integer.valueOf(672));
            hashMap.put("KP", Integer.valueOf(850));
            hashMap.put("MP", Integer.valueOf(1));
            hashMap.put("NO", Integer.valueOf(47));
            hashMap.put("OM", Integer.valueOf(968));
            hashMap.put("PK", Integer.valueOf(92));
            hashMap.put("PW", Integer.valueOf(680));
            hashMap.put("PS", Integer.valueOf(970));
            hashMap.put("PA", Integer.valueOf(507));
            hashMap.put("PG", Integer.valueOf(675));
            hashMap.put("PY", Integer.valueOf(595));
            hashMap.put("PE", Integer.valueOf(51));
            hashMap.put("PH", Integer.valueOf(63));
            hashMap.put("PL", Integer.valueOf(48));
            hashMap.put("PT", Integer.valueOf(351));
            hashMap.put("PR", Integer.valueOf(1));
            hashMap.put("QA", Integer.valueOf(974));
            hashMap.put("RE", Integer.valueOf(262));
            hashMap.put("RO", Integer.valueOf(40));
            hashMap.put("RU", Integer.valueOf(7));
            hashMap.put("RW", Integer.valueOf(SQLiteDatabase.MAX_SQL_CACHE_SIZE));
            hashMap.put("BL", Integer.valueOf(590));
            hashMap.put("SH", Integer.valueOf(290));
            hashMap.put("KN", Integer.valueOf(1));
            hashMap.put("LC", Integer.valueOf(1));
            hashMap.put("MF", Integer.valueOf(590));
            hashMap.put("PM", Integer.valueOf(508));
            hashMap.put("VC", Integer.valueOf(1));
            hashMap.put("WS", Integer.valueOf(685));
            hashMap.put("SM", Integer.valueOf(378));
            hashMap.put("ST", Integer.valueOf(239));
            hashMap.put("SA", Integer.valueOf(966));
            hashMap.put("SN", Integer.valueOf(221));
            hashMap.put("RS", Integer.valueOf(381));
            hashMap.put("SC", Integer.valueOf(248));
            hashMap.put("SL", Integer.valueOf(232));
            hashMap.put("SG", Integer.valueOf(65));
            hashMap.put("SX", Integer.valueOf(1));
            hashMap.put("SK", Integer.valueOf(421));
            hashMap.put("SI", Integer.valueOf(386));
            hashMap.put("SB", Integer.valueOf(677));
            hashMap.put("SO", Integer.valueOf(252));
            hashMap.put("ZA", Integer.valueOf(27));
            hashMap.put("GS", Integer.valueOf(500));
            hashMap.put("KR", Integer.valueOf(82));
            hashMap.put("SS", Integer.valueOf(211));
            hashMap.put("ES", Integer.valueOf(34));
            hashMap.put("LK", Integer.valueOf(94));
            hashMap.put("SD", Integer.valueOf(249));
            hashMap.put("SR", Integer.valueOf(597));
            hashMap.put("SJ", Integer.valueOf(47));
            hashMap.put("SZ", Integer.valueOf(268));
            hashMap.put("SE", Integer.valueOf(46));
            hashMap.put("CH", Integer.valueOf(41));
            hashMap.put("SY", Integer.valueOf(963));
            hashMap.put("TW", Integer.valueOf(886));
            hashMap.put("TJ", Integer.valueOf(992));
            hashMap.put("TZ", Integer.valueOf(255));
            hashMap.put("TH", Integer.valueOf(66));
            hashMap.put("TG", Integer.valueOf(228));
            hashMap.put("TK", Integer.valueOf(690));
            hashMap.put("TO", Integer.valueOf(676));
            hashMap.put("TT", Integer.valueOf(1));
            hashMap.put("TN", Integer.valueOf(216));
            hashMap.put("TR", Integer.valueOf(90));
            hashMap.put("TM", Integer.valueOf(993));
            hashMap.put("TC", Integer.valueOf(1));
            hashMap.put("TV", Integer.valueOf(688));
            hashMap.put("VI", Integer.valueOf(1));
            hashMap.put("UG", Integer.valueOf(256));
            hashMap.put("UA", Integer.valueOf(380));
            hashMap.put("AE", Integer.valueOf(971));
            hashMap.put("GB", Integer.valueOf(44));
            hashMap.put("US", Integer.valueOf(1));
            hashMap.put("UY", Integer.valueOf(598));
            hashMap.put("UZ", Integer.valueOf(998));
            hashMap.put("VU", Integer.valueOf(678));
            hashMap.put("VA", Integer.valueOf(379));
            hashMap.put("VE", Integer.valueOf(58));
            hashMap.put("VN", Integer.valueOf(84));
            hashMap.put("WF", Integer.valueOf(681));
            hashMap.put("EH", Integer.valueOf(212));
            hashMap.put("YE", Integer.valueOf(967));
            hashMap.put("ZM", Integer.valueOf(260));
            hashMap.put("ZW", Integer.valueOf(263));
        }
        return hashMap;
    }

    /* renamed from: b */
    public static Integer m10536b(String str) {
        if (str == null) {
            return null;
        }
        return (Integer) f9448e.get(str.toUpperCase(Locale.getDefault()));
    }

    /* renamed from: a */
    private static String m10531a(String str, String str2) {
        StringBuilder sb = new StringBuilder();
        sb.append("^\\+?");
        sb.append(str2);
        return str.replaceFirst(sb.toString(), "");
    }

    /* renamed from: b */
    private static Locale m10537b(Context context) {
        TelephonyManager telephonyManager = (TelephonyManager) context.getSystemService("phone");
        String simCountryIso = telephonyManager != null ? telephonyManager.getSimCountryIso() : null;
        if (TextUtils.isEmpty(simCountryIso)) {
            return null;
        }
        return new Locale("", simCountryIso);
    }

    /* renamed from: c */
    private static Locale m10540c() {
        return Locale.getDefault();
    }
}
